blog/base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home),
    path('post/<int:id>', views.post),
    path('opinions/', views.opinions),
    #clasificados
    path('created/', views.created_classified),
    path('created/<int:id>', views.created_classified),
    path('comment/', views.comment),
    #registro, inicio, cierre de sesion
    path('login/', views.loginPage),
    path('register/', views.registerPage),
    path('logout/', views.logoutPage),
    #autores
    path('author1/', views.author1),
    path('author2/', views.author2),
    path('author3/', views.author3),
    path('author4/', views.author4),
    path('author5/', views.author5),
    #clasificacion de noticias
    path('present/', views.present),
    path('police/', views.police),
    path('sports/', views.sports),
    path('technology/', views.technology),
    path('economy/', views.economy),
    path('classified/', views.classified),
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('api/', include('base.api.urls'))
]

blog/base/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Categoty(models.Model):
    classification = models.CharField(max_length = 200, null = False, blank = False)
    

    def __str__(self):
        return self.classification


class Author(models.Model):
    name = models.CharField(max_length = 200, null = False, blank = False)
    last_name = models.CharField(max_length = 200, null = False, blank = False)
    comment = models.TextField()
    category = models.ForeignKey(Categoty, on_delete = models.SET_NULL, null = True, blank = True)
    updated = models.DateTimeField(auto_now = True)
    created = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length = 200)
    description = models.TextField()
    text = models.TextField()
    author = models.ForeignKey(Author, on_delete = models.SET_NULL, null = True)
    category = models.ForeignKey(Categoty, on_delete = models.SET_NULL, null = True, blank = False)
    updated = models.DateTimeField(auto_now = True)
    created = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.title


#opiniones sobre post
class Opinions(models.Model):
    text = models.TextField()
    user = models.ForeignKey(User, null = True, on_delete = models.SET_NULL)
    post = models.ForeignKey(Post, on_delete = models.CASCADE)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text


class Classified(models.Model):
    title = models.CharField(max_length = 150, null = False, blank = False)
    text = models.TextField()
    user = models.ForeignKey(User, on_delete = models.CASCADE, null = False)
    updated = models.DateTimeField(auto_now = True)
    created = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.title


#comentarios sobre clasificados
class Comment(models.Model):
    text = models.TextField()
    user = models.ForeignKey(User, null = True, on_delete = models.SET_NULL)
    classified = models.ForeignKey(Classified, null = True, on_delete = models.CASCADE)
    updated = models.DateTimeField(auto_now = True)
    created = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.text

blog/templates/author.html
{% extends 'layouts/main.html' %}
{% load static %}

{% block content %}

{% for a in author %}

<h2>Conozca a nuestros autores</h2>
<h2>{{ a.name }}  {{ a.last_name }}</h2>
<h4>{{ a.category }}</h4>
<p>{{ a.comment }}</p>

{% endfor %}

{% for p in posts %}

<h2>Todas las noticias escritas por el:</h2>
<h3>{{ p.title }}</h3>
<h6>{{ p.category }} {{ p.created }} {{ p.author }}</h6>
<p>{{ p.description }}</p>
<h4><a href="/post/{{p.id}}">Continuar leyendo</a></h4>

{% endfor %}

{% endblock %}

blog/templates/category.html
{% extends 'layouts/main.html' %}
{% load static %}

{% block content %}

{% for p in posts %}

<h1>{{ p.category }}</h1>

<h3>{{ p.title }}</h3>
<h6>{{ p.category }} {{ p.created }} {{ p.author }}</h6>
<p>{{ p.description }}</p>
<h4><a href="/post/{{p.id}}">Continuar leyendo</a></h4>

{% endfor %}

{% endblock %}

blog/templates/classified.html
{% extends 'layouts/main.html' %}
{% load static %}

{% block content %}

<h1>Anuncios clasificados</h1>

{% for c in classifieds %}

<h2>{{ c.user }} escribio:</h2>
<h3>{{ c.title }}</h3>
<p>{{ c.text }}</p>

    {% if request.user.is_authenticated and request.user == c.user%}
        <a href="/created/{{c.id}}">Editar</a>
    {% endif %}

    {% for p in c.comment_set.all %}
        <p> {{p.user.username}} Escribió : {{p.text}}</p>
    {%endfor%}

    {% if request.user.is_authenticated %}
    <form method="POST" action="/comment/">
        {% csrf_token %}
        <input type="hidden" value="{{c.id}}" name="classifieds">
        <div class="form-group my-3">
            <textarea class="form-control" name="text" placeholder="Escibe un comentario"></textarea>
        </div>
        <button class="btn btn-primary" type="submit">Comentar</button>

    </form>
    {%endif%}

{% endfor %}

{% endblock %}

blog/templates/created.html
{% extends "layouts/main.html" %}

{% block content %}


<h3> Nuevo anuncio clasificado </h3>

<form method="POST" action="">
    {% csrf_token %}

    {% if classified is not None %}
        <input type="hidden" value="{{ classified.id }}" name="id">
    {% endif %}

    <div class="form-group my-3">
        <label>Titulo</label>
        <input type="text" class="form-control" name="title" placeholder="Titulo" 
        {% if classified is not None %}
            value="{{ classified.title }}"
        {% endif %}>
    </div>

    <div class="form-group my-3">
        <label>Texto</label>
        <textarea class="form-control" name="text">{% if classified is not None %}{{ classified.text }}{% endif %}</textarea>
    </div>
    <button class="btn btn-primary" type="submit">Enviar</button>
</form>

{% endblock %}

blog/templates/home.html
{% extends 'layouts/main.html' %}
{% load static %}

{% block content %}

{% for p in posts %}

<h3>{{ p.title }}</h3>
<h6>{{ p.category }} {{ p.created }}{{ p.author }}</h6>
<p>{{ p.description }}</p>
<h4><a href="/post/{{p.id}}">Continuar leyendo</a></h4>

{% endfor %}


{% endblock %}

blog/templates/login.html
{% extends 'layouts/main.html' %}


{% block content %}

<h2>Iniciar Sesion</h2>

<form method="POST" action="">
    {% csrf_token %}
    <div class="form-group my-3">
        <label>Usuario</label>
        <input type="text" class="form-control" name="username" placeholder="Nombre de usuario">
    </div>
    <div class="form-group my-3">
        <label>Contraseña</label>
        <input type="password" class="form-control" name="password" placeholder="Contraseña">
    </div>
    <div>
        <a href="/register">Crear cuenta nueva, aún no estoy registrado</a>
    </div>
    <button class="btn btn-primary my-3" type="submit">Iniciar sesión</button>

</form>


{% endblock %}

blog/templates/post.html
{% extends 'layouts/main.html' %}

{% block content %}

    {% for p in post %}
        <h2>{{ p.title }}</h2>

        <h6>{{ p.category }}</h6>

        <h4>{{ p.description }}</h4>

        <p>{{ p.text }}</p>

        <h5>{{ p.author }}</h5>

        <div>
            {% for c in p.opinions_set.all %}
                <p> {{ c.user.username }} Escribió : </p>
                <p>{{c.text}}</p>
            {%endfor%}
        </div>
        
        <div>
            {% if request.user.is_authenticated %}
                <form method="POST" action="/opinions/">
                    {% csrf_token %}
                    <input type="hidden" value="{{p.id}}" name="post" >
                    <div class="form-group my-3">
                        <textarea class="form-control" name="text" placeholder="Escibe un comentario"></textarea>
                    </div>
                    <button class="btn btn-primary" type="submit">Comentar</button>

                </form>
            {% endif %}
        </div>
    {% endfor %}

{% endblock %}

blog/templates/register.html
{% extends 'layouts/main.html' %}


{% block content %}

<h2>Nuevo usaurio</h2>

<form method="POST" action="">
    {% csrf_token %}
    <div class="form-group my-3">
        <label>Nombre de usuario</label>
        <input type="text" class="form-control" name="username" placeholder="Nombre de usuario">
    </div>
    <div class="form-group my-3">
        <label>Nombre</label>
        <input type="text" class="form-control" name="name" placeholder="Nombre">
    </div>
    <div class="form-group my-3">
        <label>Apellido</label>
        <input type="text" class="form-control" name="last_name" placeholder="Apellido">
    </div>
    <div class="form-group my-3">
        <label>Mail</label>
        <input type="email" class="form-control" name="email" placeholder="Email">
    </div>
    <div class="form-group my-3">
        <label>Contraseña</label>
        <input type="password" class="form-control" name="password" placeholder="Contraseña">
    </div>
    <div class="form-group my-3">
        <label>Confirmar contraseña</label>
        <input type="password" class="form-control" name="confirm_password" placeholder="Repite la contraseña">
    </div>
    <button class="btn btn-primary" type="submit">Registrarme</button>

</form>

{% endblock %}